package com.example.fitness_tracking_app.common

object FirebasePaths {
    const val USER = "user"
    const val JOINT_ACTIVITY_MAP = "jointActivityMap"
    const val NAME = "name"
    const val PROFILE_PHOTO = "profilePhoto"
    const val USERNAME = "username"
    const val PROFILE_PLACEHOLDER_PHOTO = "profilePlaceholderPhoto"
    const val BACKGROUND_PLACEHOLDER_PHOTO = "backgroundPlaceholderPhoto"
    const val BACKGROUND_PHOTO = "backgroundPhoto"
    const val EMAIL = "email"
    const val UID = "uid"
    const val ACTIVE_ACCOUNT = "activeAccount"
    const val USER_DATA = "userData"
    const val DELETED_ACCOUNT = "deletedAccount"
    const val PERSONAL_DATA = "personalData"
    const val GENDER = "gender"
    const val PHONE_NUMBER = "phoneNumber"
    const val WEIGHT_LIST = "weightList"
    const val HEIGHT = "height"
    const val BIRTHDAY = "birthday"
    const val SETTINGS_DATA = "settingsData"
    const val ACTIVE_STATUS = "active_status"
    const val CHAT = "chat"
    const val MESSAGES_MAP = "messagesMap"
    const val CHAT_METADATA = "chatMetadata"
    const val MESSAGES = "messages"
    const val LAST_READ = "lastRead"
    const val FRIENDS = "friends"
    const val RUNNING = "running"
    const val PACE = "pace"
    const val DISTANCE = "distance"
    const val DURATION = "duration"
    const val IMAGE = "image"
    const val CALORIES = "calories"
    const val LOCATION_POINT = "locationPoint"
    const val LONGITUDE = "longitude"
    const val LATITUDE = "latitude"
    const val ACTIVITY_LIST = "activityList"
    const val RUNS_LIST = "runsList"
    const val PLACE = "place"
}